# .github/workflows/tests.yml
name: Test-format-pre_commit
on: push
jobs:
  format-checker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: '3.10'
        activate-environment: mpxradar
        channels: conda-forge,bioconda,defaults
        channel-priority: true
    - run: pip install flake8 black zimports poetry
    - name: Run format checks
      uses: pre-commit/action@v3.0.0
      with:
        extra_args: -c .pre-commit-config.yaml --all-files
